#ifndef FRIENDSHUB_CORE_H
#define FRIENDSHUB_CORE_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Generated by cbindgen from friendshub-core. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define FH_ABI_VERSION 1

/**
 * Length of the base nonce shared by all chunks of one file.
 */
#define FH_BASE_NONCE_LEN 4

/**
 * How long a cached device list is considered fresh.
 */
#define FH_CACHE_TTL_SECS 300

/**
 * Number of one-time prekeys generated on first setup.
 */
#define FH_INITIAL_OTK_COUNT 100

/**
 * Length of the symmetric key.
 */
#define FH_KEY_LEN 32

/**
 * Minimum pool size below which `ensure_prekeys` tops up.
 */
#define FH_MIN_OTK_THRESHOLD 10

/**
 * Length of the Poly1305 authentication tag appended to every sealed chunk.
 */
#define FH_TAG_LEN 16

/**
 * Opaque to C. One handle drives one account: its own runtime, its own
 * database, its own websocket.
 */
typedef struct FH_FhHandle FH_FhHandle;

/**
 * A byte buffer passed across the FFI boundary.
 *
 * Callers must release it with fh_buffer_free. An empty buffer is
 * { data: null, len: 0, cap: 0 }.
 */
typedef struct FH_FhBuffer {
    uint8_t *data;
    size_t len;
    size_t cap;
} FH_FhBuffer;

const char *fh_abi_string(void);

uint32_t fh_abi_version(void);

/**
 * Releases the database row for a durable event and, where the event is an
 * incoming envelope, sends the matching receipt.
 *
 * # Safety
 *
 * `handle` must be a live pointer from `fh_init`.
 */
int32_t fh_ack_event(struct FH_FhHandle *handle, uint64_t event_id);

/**
 * Releases a buffer returned by any other `fh_*` call.
 *
 * # Safety
 *
 * `buf` must be either null or a pointer to an `FhBuffer` that was
 * returned by this library and has not been released yet. After the call
 * the buffer is reset to empty, so a second call on the same value is
 * safe and does nothing.
 */
void fh_buffer_free(struct FH_FhBuffer *buf);

/**
 * Invokes one method by id. See docs/ffi.md for the method table.
 *
 * # Safety
 *
 * - `handle` must be a live pointer from `fh_init`.
 * - `req` must point to at least `req_len` readable bytes, or be null
 *   with `req_len == 0`.
 * - `out` must be a valid, writable pointer; it is always written to and
 *   must be freed with `fh_buffer_free`.
 */
int32_t fh_call(struct FH_FhHandle *handle, uint32_t method_id, const uint8_t *req, size_t req_len, struct FH_FhBuffer *out);

/**
 * Destroys a handle and everything it owns.
 *
 * # Safety
 *
 * `handle` must be either null or a pointer returned by `fh_init` that
 * has not been destroyed yet. Passing the same non-null pointer twice is
 * undefined behaviour.
 */
void fh_destroy(struct FH_FhHandle *handle);

/**
 * Initialises a handle for one account.
 *
 * # Safety
 *
 * - `config_json` must point to at least `config_len` readable bytes, or
 *   be null with `config_len == 0`.
 * - `out_handle` and `out` must be valid, writable pointers.
 * - `out_handle` is written to on success; on failure it stays null.
 * - `out` is always written to. Callers must free it with
 *   `fh_buffer_free` when the return code is zero or one.
 */
int32_t fh_init(const uint8_t *config_json, size_t config_len, struct FH_FhHandle **out_handle, struct FH_FhBuffer *out);

/**
 * Blocks up to `timeout_ms` for the next event.
 *
 * On timeout returns 0 with an empty buffer. On any other outcome the
 * buffer carries a JSON event.
 *
 * # Safety
 *
 * - `handle` must be a live pointer from `fh_init`.
 * - `out` must be a valid, writable pointer; it is always written to and
 *   must be freed with `fh_buffer_free`.
 */
int32_t fh_poll_event(struct FH_FhHandle *handle, uint32_t timeout_ms, struct FH_FhBuffer *out);

#endif  /* FRIENDSHUB_CORE_H */
