#ifndef FRIENDSHUB_CORE_H
#define FRIENDSHUB_CORE_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Generated by cbindgen from friendshub-core. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define FH_ABI_VERSION 1

/**
 * Number of one-time prekeys generated on first setup.
 */
#define FH_INITIAL_OTK_COUNT 100

/**
 * Minimum pool size below which `ensure_prekeys` tops up.
 */
#define FH_MIN_OTK_THRESHOLD 10

/**
 * Opaque to C. One handle drives one account: its own runtime, its own
 * database, its own websocket.
 */
typedef struct FH_FhHandle FH_FhHandle;

/**
 * A byte buffer passed across the FFI boundary.
 *
 * Callers must release it with fh_buffer_free. An empty buffer is
 * { data: null, len: 0, cap: 0 }.
 */
typedef struct FH_FhBuffer {
    uint8_t *data;
    size_t len;
    size_t cap;
} FH_FhBuffer;

const char *fh_abi_string(void);

uint32_t fh_abi_version(void);

/**
 * Releases the database row for a durable event and, where the event is an
 * incoming envelope, sends the matching receipt.
 */
int32_t fh_ack_event(struct FH_FhHandle *handle, uint64_t event_id);

void fh_buffer_free(struct FH_FhBuffer *buf);

int32_t fh_call(struct FH_FhHandle *handle, uint32_t method_id, const uint8_t *req, size_t req_len, struct FH_FhBuffer *out);

void fh_destroy(struct FH_FhHandle *handle);

int32_t fh_init(const uint8_t *config_json, size_t config_len, struct FH_FhHandle **out_handle, struct FH_FhBuffer *out);

/**
 * Blocks up to timeout_ms for the next event. On timeout returns 0 with an
 * empty buffer. On any other outcome the buffer carries a JSON event.
 */
int32_t fh_poll_event(struct FH_FhHandle *handle, uint32_t timeout_ms, struct FH_FhBuffer *out);

#endif  /* FRIENDSHUB_CORE_H */
